name: xyz
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  sizer: ^2.0.15
  carousel_slider: ^4.1.1
  carousel_pro: ^1.0.0
  splashscreen: ^1.3.5
  flutter_svg: ^1.1.1
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  jwt_decoder: ^2.0.1
  google_sign_in: ^5.4.0
  http:
  get_storage: ^2.0.3
  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0
  just_audio: ^0.9.28
  cached_network_image: ^3.2.1
  audio_service: ^0.18.7
  get_it: ^7.2.0
  audio_video_progress_bar: ^0.10.0
  image_picker: ^0.8.5+3
  google_fonts: ^3.0.1

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/splash/
    - assets/signup_signin/
    - assets/images/
    - assets/svg/

