///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserNotificationNotifications {
/*
{
  "sendTo": "All Users",
  "isDeleted": false,
  "_id": "62a1ecebcac3a64c8dd804e4",
  "title": "first notification",
  "desc": "notification description",
  "createdAt": "2022-06-09T12:51:55.962Z",
  "updatedAt": "2022-06-09T12:51:55.962Z",
  "__v": 0
}
*/

  String? sendTo;
  bool? isDeleted;
  String? Id;
  String? title;
  String? desc;
  String? createdAt;
  String? updatedAt;
  int? V;

  UserNotificationNotifications({
    this.sendTo,
    this.isDeleted,
    this.Id,
    this.title,
    this.desc,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  UserNotificationNotifications.fromJson(Map<String, dynamic> json) {
    sendTo = json['sendTo']?.toString();
    isDeleted = json['isDeleted'];
    Id = json['_id']?.toString();
    title = json['title']?.toString();
    desc = json['desc']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['sendTo'] = sendTo;
    data['isDeleted'] = isDeleted;
    data['_id'] = Id;
    data['title'] = title;
    data['desc'] = desc;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

class UserNotification {
/*
{
  "status": true,
  "results": 1,
  "message": "all notifications",
  "notifications": [
    {
      "sendTo": "All Users",
      "isDeleted": false,
      "_id": "62a1ecebcac3a64c8dd804e4",
      "title": "first notification",
      "desc": "notification description",
      "createdAt": "2022-06-09T12:51:55.962Z",
      "updatedAt": "2022-06-09T12:51:55.962Z",
      "__v": 0
    }
  ]
}
*/

  bool? status;
  int? results;
  String? message;
  List<UserNotificationNotifications?>? notifications;

  UserNotification({
    this.status,
    this.results,
    this.message,
    this.notifications,
  });
  UserNotification.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    results = json['results']?.toInt();
    message = json['message']?.toString();
    if (json['notifications'] != null) {
      final v = json['notifications'];
      final arr0 = <UserNotificationNotifications>[];
      v.forEach((v) {
        arr0.add(UserNotificationNotifications.fromJson(v));
      });
      notifications = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['results'] = results;
    data['message'] = message;
    if (notifications != null) {
      final v = notifications;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['notifications'] = arr0;
    }
    return data;
  }
}
