///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OnBoardingCategoriesUpdateUser {
/*
{
  "name": "Unknown",
  "phone": "+917042659990",
  "email": "testuser@gmail.com",
  "image": "https://i.pinimg.com/originals/6e/70/97/6e7097e29b6bc038069e5b375069c1c7.jpg",
  "userType": "user",
  "category": [
    "62a086dbb2d9256900e55230"
  ],
  "active": true,
  "isDeleted": false,
  "_id": "62d1253b616b4e4268941a4b",
  "firebaseUid": "rrTSq5BNgleBaHYfVl1KbqgBVBD2",
  "firebaseSignInProvider": "phone",
  "createdAt": "2022-07-15T08:28:43.312Z",
  "updatedAt": "2022-07-19T20:28:05.836Z",
  "__v": 0
}
*/

  String? name;
  String? phone;
  String? email;
  String? image;
  String? userType;
  List<String?>? category;
  bool? active;
  bool? isDeleted;
  String? Id;
  String? firebaseUid;
  String? firebaseSignInProvider;
  String? createdAt;
  String? updatedAt;
  int? V;

  OnBoardingCategoriesUpdateUser({
    this.name,
    this.phone,
    this.email,
    this.image,
    this.userType,
    this.category,
    this.active,
    this.isDeleted,
    this.Id,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  OnBoardingCategoriesUpdateUser.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    phone = json['phone']?.toString();
    email = json['email']?.toString();
    image = json['image']?.toString();
    userType = json['userType']?.toString();
    if (json['category'] != null) {
      final v = json['category'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      category = arr0;
    }
    active = json['active'];
    isDeleted = json['isDeleted'];
    Id = json['_id']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['phone'] = phone;
    data['email'] = email;
    data['image'] = image;
    data['userType'] = userType;
    if (category != null) {
      final v = category;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['category'] = arr0;
    }
    data['active'] = active;
    data['isDeleted'] = isDeleted;
    data['_id'] = Id;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

class OnBoardingCategoriesUpdate {
/*
{
  "status": true,
  "message": "User onboarded.",
  "user": {
    "name": "Unknown",
    "phone": "+917042659990",
    "email": "testuser@gmail.com",
    "image": "https://i.pinimg.com/originals/6e/70/97/6e7097e29b6bc038069e5b375069c1c7.jpg",
    "userType": "user",
    "category": [
      "62a086dbb2d9256900e55230"
    ],
    "active": true,
    "isDeleted": false,
    "_id": "62d1253b616b4e4268941a4b",
    "firebaseUid": "rrTSq5BNgleBaHYfVl1KbqgBVBD2",
    "firebaseSignInProvider": "phone",
    "createdAt": "2022-07-15T08:28:43.312Z",
    "updatedAt": "2022-07-19T20:28:05.836Z",
    "__v": 0
  }
}
*/

  bool? status;
  String? message;
  OnBoardingCategoriesUpdateUser? user;

  OnBoardingCategoriesUpdate({
    this.status,
    this.message,
    this.user,
  });
  OnBoardingCategoriesUpdate.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    user = (json['user'] != null) ? OnBoardingCategoriesUpdateUser.fromJson(json['user']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }
}
