///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SearchTrackTracks {
/*
{
  "artist": "Allayya",
  "tags": [
    "hindi"
  ],
  "thumbnailImage": "https://track-thumnails.s3.us-west-1.amazonaws.com/track1.jpg",
  "isDeleted": false,
  "_id": "62bd9cfaf96997dfc841c379",
  "audioTrack": "https://allayya-tracks.s3.us-west-1.amazonaws.com/ethereal-meditation-airy-and-tranquil-110249.mp3",
  "desc": "This is a song.",
  "subCategoryId": "62bd5226f96997dfc841c364",
  "title": "Ethereal meditation airy and tranquil"
}
*/

  String? artist;
  List<String?>? tags;
  String? thumbnailImage;
  bool? isDeleted;
  String? Id;
  String? audioTrack;
  String? desc;
  String? subCategoryId;
  String? title;

  SearchTrackTracks({
    this.artist,
    this.tags,
    this.thumbnailImage,
    this.isDeleted,
    this.Id,
    this.audioTrack,
    this.desc,
    this.subCategoryId,
    this.title,
  });
  SearchTrackTracks.fromJson(Map<String, dynamic> json) {
    artist = json['artist']?.toString();
    if (json['tags'] != null) {
      final v = json['tags'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      tags = arr0;
    }
    thumbnailImage = json['thumbnailImage']?.toString();
    isDeleted = json['isDeleted'];
    Id = json['_id']?.toString();
    audioTrack = json['audioTrack']?.toString();
    desc = json['desc']?.toString();
    subCategoryId = json['subCategoryId']?.toString();
    title = json['title']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['artist'] = artist;
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['tags'] = arr0;
    }
    data['thumbnailImage'] = thumbnailImage;
    data['isDeleted'] = isDeleted;
    data['_id'] = Id;
    data['audioTrack'] = audioTrack;
    data['desc'] = desc;
    data['subCategoryId'] = subCategoryId;
    data['title'] = title;
    return data;
  }
}

class SearchTrack {
/*
{
  "status": true,
  "results": 4,
  "message": "all tracks",
  "tracks": [
    {
      "artist": "Allayya",
      "tags": [
        "hindi"
      ],
      "thumbnailImage": "https://track-thumnails.s3.us-west-1.amazonaws.com/track1.jpg",
      "isDeleted": false,
      "_id": "62bd9cfaf96997dfc841c379",
      "audioTrack": "https://allayya-tracks.s3.us-west-1.amazonaws.com/ethereal-meditation-airy-and-tranquil-110249.mp3",
      "desc": "This is a song.",
      "subCategoryId": "62bd5226f96997dfc841c364",
      "title": "Ethereal meditation airy and tranquil"
    }
  ]
}
*/

  bool? status;
  int? results;
  String? message;
  List<SearchTrackTracks?>? tracks;

  SearchTrack({
    this.status,
    this.results,
    this.message,
    this.tracks,
  });
  SearchTrack.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    results = json['results']?.toInt();
    message = json['message']?.toString();
    if (json['tracks'] != null) {
      final v = json['tracks'];
      final arr0 = <SearchTrackTracks>[];
      v.forEach((v) {
        arr0.add(SearchTrackTracks.fromJson(v));
      });
      tracks = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['results'] = results;
    data['message'] = message;
    if (tracks != null) {
      final v = tracks;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['tracks'] = arr0;
    }
    return data;
  }
}
