///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class userDeteailsCategoriesSubCategories {
/*
{
  "coverImage": "https://track-sub-category-images.s3.us-west-1.amazonaws.com/basic+meditation.jpg",
  "numOfTracks": 1,
  "isDeleted": false,
  "_id": "62bd5226f96997dfc841c364",
  "categoryId": "62bd4a5ec532b23e72eb6304",
  "desc": "This is your sound Sub Category",
  "name": "Basic Meditation",
  "id": "62bd5226f96997dfc841c364"
}
*/

  String? coverImage;
  int? numOfTracks;
  bool? isDeleted;
  String? Id;
  String? categoryId;
  String? desc;
  String? name;
  String? id;

  userDeteailsCategoriesSubCategories({
    this.coverImage,
    this.numOfTracks,
    this.isDeleted,
    this.Id,
    this.categoryId,
    this.desc,
    this.name,
    this.id,
  });
  userDeteailsCategoriesSubCategories.fromJson(Map<String, dynamic> json) {
    coverImage = json['coverImage']?.toString();
    numOfTracks = json['numOfTracks']?.toInt();
    isDeleted = json['isDeleted'];
    Id = json['_id']?.toString();
    categoryId = json['categoryId']?.toString();
    desc = json['desc']?.toString();
    name = json['name']?.toString();
    id = json['id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['coverImage'] = coverImage;
    data['numOfTracks'] = numOfTracks;
    data['isDeleted'] = isDeleted;
    data['_id'] = Id;
    data['categoryId'] = categoryId;
    data['desc'] = desc;
    data['name'] = name;
    data['id'] = id;
    return data;
  }
}

class userDeteailsCategories {
/*
{
  "coverImage": "https://track-category-images.s3.us-west-1.amazonaws.com/Frame+115.png",
  "isDeleted": false,
  "_id": "62bd4a5ec532b23e72eb6304",
  "desc": "This is meditation category.",
  "name": "Meditation",
  "subCategories": [
    {
      "coverImage": "https://track-sub-category-images.s3.us-west-1.amazonaws.com/basic+meditation.jpg",
      "numOfTracks": 1,
      "isDeleted": false,
      "_id": "62bd5226f96997dfc841c364",
      "categoryId": "62bd4a5ec532b23e72eb6304",
      "desc": "This is your sound Sub Category",
      "name": "Basic Meditation",
      "id": "62bd5226f96997dfc841c364"
    }
  ],
  "id": "62bd4a5ec532b23e72eb6304"
}
*/

  String? coverImage;
  bool? isDeleted;
  String? Id;
  String? desc;
  String? name;
  List<userDeteailsCategoriesSubCategories?>? subCategories;
  String? id;

  userDeteailsCategories({
    this.coverImage,
    this.isDeleted,
    this.Id,
    this.desc,
    this.name,
    this.subCategories,
    this.id,
  });
  userDeteailsCategories.fromJson(Map<String, dynamic> json) {
    coverImage = json['coverImage']?.toString();
    isDeleted = json['isDeleted'];
    Id = json['_id']?.toString();
    desc = json['desc']?.toString();
    name = json['name']?.toString();
    if (json['subCategories'] != null) {
      final v = json['subCategories'];
      final arr0 = <userDeteailsCategoriesSubCategories>[];
      v.forEach((v) {
        arr0.add(userDeteailsCategoriesSubCategories.fromJson(v));
      });
      subCategories = arr0;
    }
    id = json['id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['coverImage'] = coverImage;
    data['isDeleted'] = isDeleted;
    data['_id'] = Id;
    data['desc'] = desc;
    data['name'] = name;
    if (subCategories != null) {
      final v = subCategories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['subCategories'] = arr0;
    }
    data['id'] = id;
    return data;
  }
}

class userDeteails {
/*
{
  "status": true,
  "results": 9,
  "message": "all categories",
  "categories": [
    {
      "coverImage": "https://track-category-images.s3.us-west-1.amazonaws.com/Frame+115.png",
      "isDeleted": false,
      "_id": "62bd4a5ec532b23e72eb6304",
      "desc": "This is meditation category.",
      "name": "Meditation",
      "subCategories": [
        {
          "coverImage": "https://track-sub-category-images.s3.us-west-1.amazonaws.com/basic+meditation.jpg",
          "numOfTracks": 1,
          "isDeleted": false,
          "_id": "62bd5226f96997dfc841c364",
          "categoryId": "62bd4a5ec532b23e72eb6304",
          "desc": "This is your sound Sub Category",
          "name": "Basic Meditation",
          "id": "62bd5226f96997dfc841c364"
        }
      ],
      "id": "62bd4a5ec532b23e72eb6304"
    }
  ]
}
*/

  bool? status;
  int? results;
  String? message;
  List<userDeteailsCategories?>? categories;

  userDeteails({
    this.status,
    this.results,
    this.message,
    this.categories,
  });
  userDeteails.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    results = json['results']?.toInt();
    message = json['message']?.toString();
    if (json['categories'] != null) {
      final v = json['categories'];
      final arr0 = <userDeteailsCategories>[];
      v.forEach((v) {
        arr0.add(userDeteailsCategories.fromJson(v));
      });
      categories = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['results'] = results;
    data['message'] = message;
    if (categories != null) {
      final v = categories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['categories'] = arr0;
    }
    return data;
  }
}
