///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TrackListTracks {
/*
{
  "_id": "62d90701d30bd9910b81dfb2",
  "artist": "Admin",
  "tags": [
    "etw"
  ],
  "thumbnailImage": "https://track-thumnails.s3.us-west-1.amazonaws.com/allayya-thubmnail-pexels-kindel-media-7054549.jpg",
  "duration": "2.86",
  "favouritesOf": [
    "62d1253b616b4e4268941a4b"
  ],
  "isDeleted": false,
  "subCategoryId": "62d8f352d30bd9910b81dd24",
  "title": "etw",
  "desc": "etwwwwww",
  "audioTrack": "https://allayya-tracks.s3.us-west-1.amazonaws.com/allayya-track-Sirnawa%20-%20Ammy%20Virk.mp3",
  "createdAt": "2022-07-21T07:57:53.051Z",
  "updatedAt": "2022-07-21T13:23:38.716Z",
  "__v": 2,
  "isFavourite": false
}
*/

  String? Id;
  String? artist;
  List<String?>? tags;
  String? thumbnailImage;
  String? duration;
  List<String?>? favouritesOf;
  bool? isDeleted;
  String? subCategoryId;
  String? title;
  String? desc;
  String? audioTrack;
  String? createdAt;
  String? updatedAt;
  int? V;
  bool? isFavourite;

  TrackListTracks({
    this.Id,
    this.artist,
    this.tags,
    this.thumbnailImage,
    this.duration,
    this.favouritesOf,
    this.isDeleted,
    this.subCategoryId,
    this.title,
    this.desc,
    this.audioTrack,
    this.createdAt,
    this.updatedAt,
    this.V,
    this.isFavourite,
  });
  TrackListTracks.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    artist = json['artist']?.toString();
    if (json['tags'] != null) {
      final v = json['tags'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      tags = arr0;
    }
    thumbnailImage = json['thumbnailImage']?.toString();
    duration = json['duration']?.toString();
    if (json['favouritesOf'] != null) {
      final v = json['favouritesOf'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      favouritesOf = arr0;
    }
    isDeleted = json['isDeleted'];
    subCategoryId = json['subCategoryId']?.toString();
    title = json['title']?.toString();
    desc = json['desc']?.toString();
    audioTrack = json['audioTrack']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
    isFavourite = json['isFavourite'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['artist'] = artist;
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['tags'] = arr0;
    }
    data['thumbnailImage'] = thumbnailImage;
    data['duration'] = duration;
    if (favouritesOf != null) {
      final v = favouritesOf;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['favouritesOf'] = arr0;
    }
    data['isDeleted'] = isDeleted;
    data['subCategoryId'] = subCategoryId;
    data['title'] = title;
    data['desc'] = desc;
    data['audioTrack'] = audioTrack;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    data['isFavourite'] = isFavourite;
    return data;
  }
}

class TrackList {
/*
{
  "status": true,
  "results": 6,
  "message": "all tracks",
  "tracks": [
    {
      "_id": "62d90701d30bd9910b81dfb2",
      "artist": "Admin",
      "tags": [
        "etw"
      ],
      "thumbnailImage": "https://track-thumnails.s3.us-west-1.amazonaws.com/allayya-thubmnail-pexels-kindel-media-7054549.jpg",
      "duration": "2.86",
      "favouritesOf": [
        "62d1253b616b4e4268941a4b"
      ],
      "isDeleted": false,
      "subCategoryId": "62d8f352d30bd9910b81dd24",
      "title": "etw",
      "desc": "etwwwwww",
      "audioTrack": "https://allayya-tracks.s3.us-west-1.amazonaws.com/allayya-track-Sirnawa%20-%20Ammy%20Virk.mp3",
      "createdAt": "2022-07-21T07:57:53.051Z",
      "updatedAt": "2022-07-21T13:23:38.716Z",
      "__v": 2,
      "isFavourite": false
    }
  ]
}
*/

  bool? status;
  int? results;
  String? message;
  List<TrackListTracks?>? tracks;

  TrackList({
    this.status,
    this.results,
    this.message,
    this.tracks,
  });
  TrackList.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    results = json['results']?.toInt();
    message = json['message']?.toString();
    if (json['tracks'] != null) {
      final v = json['tracks'];
      final arr0 = <TrackListTracks>[];
      v.forEach((v) {
        arr0.add(TrackListTracks.fromJson(v));
      });
      tracks = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['results'] = results;
    data['message'] = message;
    if (tracks != null) {
      final v = tracks;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['tracks'] = arr0;
    }
    return data;
  }
}
