///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserFavoritesFavoriteTracksTracks {
/*
{
  "artist": "Allayya",
  "tags": [
    "hindi"
  ],
  "thumbnailImage": "https://track-thumnails.s3.us-west-1.amazonaws.com/track4.jpg",
  "isDeleted": false,
  "_id": "62bd9cfaf96997dfc841c37c",
  "audioTrack": "https://allayya-tracks.s3.us-west-1.amazonaws.com/just-relax-11157.mp3",
  "desc": "This is a song.",
  "subCategoryId": "62bd5226f96997dfc841c365",
  "title": "just-relax"
}
*/

  String? artist;
  List<String?>? tags;
  String? thumbnailImage;
  bool? isDeleted;
  String? Id;
  String? audioTrack;
  String? desc;
  String? subCategoryId;
  String? title;

  UserFavoritesFavoriteTracksTracks({
    this.artist,
    this.tags,
    this.thumbnailImage,
    this.isDeleted,
    this.Id,
    this.audioTrack,
    this.desc,
    this.subCategoryId,
    this.title,
  });
  UserFavoritesFavoriteTracksTracks.fromJson(Map<String, dynamic> json) {
    artist = json['artist']?.toString();
    if (json['tags'] != null) {
      final v = json['tags'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      tags = arr0;
    }
    thumbnailImage = json['thumbnailImage']?.toString();
    isDeleted = json['isDeleted'];
    Id = json['_id']?.toString();
    audioTrack = json['audioTrack']?.toString();
    desc = json['desc']?.toString();
    subCategoryId = json['subCategoryId']?.toString();
    title = json['title']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['artist'] = artist;
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['tags'] = arr0;
    }
    data['thumbnailImage'] = thumbnailImage;
    data['isDeleted'] = isDeleted;
    data['_id'] = Id;
    data['audioTrack'] = audioTrack;
    data['desc'] = desc;
    data['subCategoryId'] = subCategoryId;
    data['title'] = title;
    return data;
  }
}

class UserFavoritesFavoriteTracks {
/*
{
  "tracks": [
    {
      "artist": "Allayya",
      "tags": [
        "hindi"
      ],
      "thumbnailImage": "https://track-thumnails.s3.us-west-1.amazonaws.com/track4.jpg",
      "isDeleted": false,
      "_id": "62bd9cfaf96997dfc841c37c",
      "audioTrack": "https://allayya-tracks.s3.us-west-1.amazonaws.com/just-relax-11157.mp3",
      "desc": "This is a song.",
      "subCategoryId": "62bd5226f96997dfc841c365",
      "title": "just-relax"
    }
  ],
  "_id": "62d6ad7a616b4e4268942efd",
  "user": "62d1253b616b4e4268941a4b",
  "createdAt": "2022-07-19T13:11:22.350Z",
  "updatedAt": "2022-07-19T14:24:29.604Z",
  "__v": 3
}
*/

  List<UserFavoritesFavoriteTracksTracks?>? tracks;
  String? Id;
  String? user;
  String? createdAt;
  String? updatedAt;
  int? V;

  UserFavoritesFavoriteTracks({
    this.tracks,
    this.Id,
    this.user,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  UserFavoritesFavoriteTracks.fromJson(Map<String, dynamic> json) {
    if (json['tracks'] != null) {
      final v = json['tracks'];
      final arr0 = <UserFavoritesFavoriteTracksTracks>[];
      v.forEach((v) {
        arr0.add(UserFavoritesFavoriteTracksTracks.fromJson(v));
      });
      tracks = arr0;
    }
    Id = json['_id']?.toString();
    user = json['user']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (tracks != null) {
      final v = tracks;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['tracks'] = arr0;
    }
    data['_id'] = Id;
    data['user'] = user;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

class UserFavorites {
/*
{
  "status": true,
  "results": 3,
  "favoriteTracks": {
    "tracks": [
      {
        "artist": "Allayya",
        "tags": [
          "hindi"
        ],
        "thumbnailImage": "https://track-thumnails.s3.us-west-1.amazonaws.com/track4.jpg",
        "isDeleted": false,
        "_id": "62bd9cfaf96997dfc841c37c",
        "audioTrack": "https://allayya-tracks.s3.us-west-1.amazonaws.com/just-relax-11157.mp3",
        "desc": "This is a song.",
        "subCategoryId": "62bd5226f96997dfc841c365",
        "title": "just-relax"
      }
    ],
    "_id": "62d6ad7a616b4e4268942efd",
    "user": "62d1253b616b4e4268941a4b",
    "createdAt": "2022-07-19T13:11:22.350Z",
    "updatedAt": "2022-07-19T14:24:29.604Z",
    "__v": 3
  }
}
*/

  bool? status;
  int? results;
  UserFavoritesFavoriteTracks? favoriteTracks;

  UserFavorites({
    this.status,
    this.results,
    this.favoriteTracks,
  });
  UserFavorites.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    results = json['results']?.toInt();
    favoriteTracks = (json['favoriteTracks'] != null) ? UserFavoritesFavoriteTracks.fromJson(json['favoriteTracks']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['results'] = results;
    if (favoriteTracks != null) {
      data['favoriteTracks'] = favoriteTracks!.toJson();
    }
    return data;
  }
}
